import type { ActivityId } from '@/features/tracking/domain/Activity';
import {
  isComplete,
  occurrenceOriginFor,
  type ActivityOccurrence,
  type OccurrenceStatus,
} from '@/features/tracking/domain/ActivityOccurrence';
import type {
  ActivitySchedule,
  ScheduleId,
} from '@/features/tracking/domain/ActivitySchedule';
import { emptyChecklistProgress } from '@/features/tracking/domain/activityTypes/checklist';
import type { CalendarDay } from '@/shared/domain/time/CalendarDay';

const activityId = (value: string): ActivityId => value as ActivityId;
const scheduleId = (value: string): ScheduleId => value as ScheduleId;
const day = (value: string): CalendarDay => value as CalendarDay;

const checklistOccurrence = (
  status: OccurrenceStatus,
): ActivityOccurrence => ({
  activityId: activityId('activity-1'),
  scheduleId: scheduleId('schedule-1'),
  date: day('2024-01-15'),
  status,
  completedAt: status === 'done' ? new Date('2024-01-15T09:00:00Z') : null,
  notes: null,
  origin: 'recurrence',
  progress: emptyChecklistProgress(),
});

describe('isComplete', () => {
  it('is true for a done occurrence', () => {
    expect(isComplete(checklistOccurrence('done'))).toBe(true);
  });

  it('is false for a pending occurrence', () => {
    expect(isComplete(checklistOccurrence('pending'))).toBe(false);
  });
});

describe('checklist progress', () => {
  it('starts empty (a checklist day tracks nothing beyond its status)', () => {
    expect(emptyChecklistProgress()).toEqual({});
  });
});

describe('occurrenceOriginFor', () => {
  const scheduleWith = (
    recurrenceRule: ActivitySchedule['recurrenceRule'],
  ): ActivitySchedule =>
    recurrenceRule.kind === 'quota'
      ? {
          id: scheduleId('schedule-1'),
          activityId: activityId('activity-1'),
          recurrenceRule,
          dayGoal: null,
          periodGoal: { aggregate: 'completedDays', amount: 3 },
          startDate: day('2024-01-01'),
        }
      : {
          id: scheduleId('schedule-1'),
          activityId: activityId('activity-1'),
          recurrenceRule,
          dayGoal: null,
          periodGoal: null,
          startDate: day('2024-01-01'),
        };

  it('marks a quota day as an opt-in (the user chose this day, §4)', () => {
    const quota = scheduleWith({ kind: 'quota', period: 'week' });
    expect(occurrenceOriginFor(quota, day('2024-06-15'))).toBe('quotaOptIn');
  });

  it('marks a due fixed day as generated by the recurrence', () => {
    const daily = scheduleWith({ kind: 'daily' });
    expect(occurrenceOriginFor(daily, day('2024-06-15'))).toBe('recurrence');
  });

  it('marks a fixed day that was not due as manual (off-schedule record)', () => {
    // 2024-06-15 is a Saturday; a Mon/Wed/Fri schedule does not generate it.
    const monWedFri = scheduleWith({ kind: 'weekly', daysOfWeek: [1, 3, 5] });
    expect(occurrenceOriginFor(monWedFri, day('2024-06-15'))).toBe('manual');
  });

  it('marks a record with no schedule at all as manual', () => {
    expect(occurrenceOriginFor(null, day('2024-06-15'))).toBe('manual');
  });
});

describe('manual occurrence (future-features invariant 3)', () => {
  it('can exist with no schedule on any date', () => {
    const manual: ActivityOccurrence = {
      ...checklistOccurrence('done'),
      scheduleId: null,
      origin: 'manual',
      date: day('2024-02-18'), // any date, even a Sunday a weekly recurrence never generated
    };
    expect(manual.scheduleId).toBeNull();
    expect(manual.origin).toBe('manual');
  });
});
